insert into clinlims.platform(id,name) values(1, 'RETROCI');
insert into clinlims.platform(id,name) values(2, 'CEPREF');
insert into clinlims.platform(id,name) values(3, 'INSP');
insert into clinlims.platform(id,name) values(4, 'CEDRES');
insert into clinlims.platform(id,name) values(5, 'CHR YAMOUSSOUKRO');
insert into clinlims.platform(id,name) values(6, 'CHR SAN PEDRO');
insert into clinlims.platform(id,name) values(7, 'CHR ABENGOUROU');
insert into clinlims.platform(id,name) values(8, 'CHR KORHOGO');
insert into clinlims.platform(id,name) values(9, 'CHU BOUAKE');
insert into clinlims.platform(id,name) values(10, 'HG GAGNOA');
insert into clinlims.platform(id,name) values(11, 'HG ABOBO SUD');
insert into clinlims.platform(id,name) values(12, 'HG SOUBRE');
insert into clinlims.platform(id,name) values(13, 'CHR DALOA');
insert into clinlims.platform(id,name) values(14, 'IPCI ADIOPODOUME');
insert into clinlims.platform(id,name) values(15, 'CHR MAN');
insert into clinlims.platform(id,name) values(16, 'CIRBA');
insert into clinlims.platform(id,name) values(17, 'CHR GAGNOA');
insert into clinlims.platform(id,name) values(18, 'CHU ANGRE');
insert into clinlims.platform(id,name) values(19, 'CMSB TORGOKAHA');
insert into clinlims.platform(id,name) values(20, 'AIBEF DALOA');
insert into clinlims.platform(id,name) values(21, 'CHR BONDOUKOU');